# action.yml
name: "Greeting"

on:
  push:
    
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'rakesh725/hello-world-docker-action'
          path: ./
      - name: list file and dir in workspace 
        working-directory: ${{ github.workspace }}  
        run: ls -la  
      - name: Hello action step
        uses: ./hello-world-docker-action
        id: hello
        with:
          who-to-greet: "Manish Pandey"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"




        ##[error]Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/actions-test/actions-test/hello-world-docker-action'. Did you forget to run actions/checkout before running your local action?
